#!/usr/bin/env python3
"""Regenerate docs/rules.md from the rule registry (single source of truth)."""

from __future__ import annotations

from pathlib import Path

from cairn.rules import all_rules

HEADER = """\
# Rule catalogue

<!-- Generated by scripts/generate_rules_doc.py — do not edit by hand. -->

Rule IDs are a stable public contract: they never change meaning and are
never reused. Disable or re-rank any rule via `.cairn.yaml`
(see [configuration.md](configuration.md)).

| ID | Severity | Category | Title |
|----|----------|----------|-------|
"""


def main() -> None:
    lines = [HEADER.rstrip("\n")]
    for rule in all_rules():
        lines.append(
            f"| [{rule.id}](#{rule.id.lower()}) | {rule.severity.value} "
            f"| {rule.category.value} | {rule.title} |"
        )
    lines.append("")
    for rule in all_rules():
        lines.append(f"## {rule.id}")
        lines.append("")
        lines.append(f"**{rule.title}** · {rule.severity.value} · {rule.category.value}")
        lines.append("")
        lines.append(rule.description)
        if rule.resource_types:
            types = ", ".join(f"`{t}`" for t in rule.resource_types)
            lines.append("")
            lines.append(f"*Applies to:* {types}")
        if rule.references:
            lines.append("")
            lines.append("*References:* " + " · ".join(rule.references))
        lines.append("")
    out = Path(__file__).resolve().parent.parent / "docs" / "rules.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(all_rules())} rules)")


if __name__ == "__main__":
    main()
